Balancer: Fee collector final deploy
mimic-fi/v2-deployments pull request #40
Opened 2023-06-01 17:08 UTC by facuspagnuolo

2023-06-01 21:54 UTC, dmf7z requested changes

2023-06-01 21:54 UTC, dmf7z commented on tasks/2023053100-balancer-fee-collector-updates-mainnet/input.ts
> +      tokenIndexConfig: defaultTokenIndexConfig,
I think we should allow it only for USDC and BAL. This way the bot does not need to know the configuration offchain and can iterate over those two tokens.

2023-06-01 21:54 UTC, dmf7z commented on tasks/2023053101-balancer-fee-collector-updates-optimism/input.ts
> +      tokenIndexConfig: defaultTokenIndexConfig,
same here, USDC and BAL

2023-06-01 21:54 UTC, dmf7z commented on tasks/2023053102-balancer-fee-collector-updates-l2/input.arbitrum.ts
> +        tokenThresholdConfig: defaultTokenThresholdConfig,
No threshold so we assure execution

2023-06-01 21:54 UTC, dmf7z commented on tasks/2023053102-balancer-fee-collector-updates-l2/input.gnosis.ts
> +        tokenThresholdConfig: defaultTokenThresholdConfig,
No threshold so we assure execution

2023-06-01 21:54 UTC, dmf7z commented on tasks/2023053102-balancer-fee-collector-updates-l2/input.polygon.ts
> +        tokenThresholdConfig: defaultTokenThresholdConfig,
No threshold so we assure execution

2023-06-01 21:54 UTC, dmf7z commented on tasks/2023053102-balancer-fee-collector-updates-l2/input.gnosis.ts
> +const OWNER = '0x09Df1626110803C7b3b07085Ef1E053494155089'
`0x14969B55a675d13a1700F71A37511bc22D90155a`

2023-06-02 12:15 UTC, facuspagnuolo commented on tasks/2023053100-balancer-fee-collector-updates-mainnet/input.ts
> +      tokenIndexConfig: defaultTokenIndexConfig,
Nice catch! These type of things will make the bot run much faster, we should bear it in mind for other cases as well

2023-06-02 12:20 UTC, facuspagnuolo commented on tasks/2023053102-balancer-fee-collector-updates-l2/input.arbitrum.ts
> +        tokenThresholdConfig: defaultTokenThresholdConfig,
Are you sure? The config doc does mention a threshold for the bridges

2023-06-02 12:55 UTC, dmf7z approved these changes

2023-06-09 21:14 UTC, merged