Paraswap: Fee redistributor updates
mimic-fi/v2-deployments pull request #42
Opened 2023-06-22 01:53 UTC by facuspagnuolo

This PR includes several changes to the actions deployed for Paraswap's fee redistributor smart vault

### Mainnet
- New `PermissionsManager` in control of the entire architecture
- Upgrade `ERC20Claimer` to support configuring the token out
- New `MetamaskClaimer` action

### Polygon, Arbitrum, Optimism, BNB
- New `PermissionsManager` in control of the entire architecture
- Upgrade `ERC20Claimer` to support configuring the token out
- New `MetamaskClaimer` action
- New `ConnextBridger` action

### Fantom
- New `PermissionsManager` in control of the entire architecture
- Upgrade `ERC20Claimer` to support configuring the token out
- New `FantomBridger` action

### Avalanche
- New `PermissionsManager` in control of the entire architecture
- Upgrade `ERC20Claimer` to support configuring the token out
- New `WormholeBridger` action

2023-06-22 13:13 UTC, dmf7z requested changes

2023-06-22 13:13 UTC, dmf7z commented on tasks/2023062100-paraswap-fee-redistributor-updates-mainnet/input.ts
> +  mimic: TESTING_EOA,
shouldn't we set directly the new admin? 
`0x26A0c29261d18C49e6Cf0Cee175018274D58f90C`
please confirm @brunitob

2023-06-22 13:22 UTC, dmf7z requested changes

2023-06-22 13:22 UTC, dmf7z commented on tasks/2023062101-paraswap-fee-redistributor-updates-polygon/index.ts
> +        target: withdrawer,
we should deprecate withdraw tasks on all networks but mainnet, right? (eg. remove the withdraw permission)

2023-06-22 13:22 UTC, dmf7z commented on tasks/2023062100-paraswap-fee-redistributor-updates-mainnet/index.ts
> +  await executePermissionChanges(
we should remove the SwapFeeSetter from all networks

2023-06-22 13:24 UTC, dmf7z commented on tasks/2023062100-paraswap-fee-redistributor-updates-mainnet/index.ts
> +  await executePermissionChanges(
Afterwards will need to configure the final fee with cap on the withdraw task on Mainnetm, right?

2023-06-22 14:22 UTC, facuspagnuolo commented on constants/tokens/bsc.ts
> +export const WETH = '0x2170Ed0880ac9A755fd29B2688956BD959F933F8'
I don't think so, `0x2170ed0880ac9a755fd29b2688956bd959f933f8` is correct

2023-06-22 14:22 UTC, facuspagnuolo commented on tasks/2023062100-paraswap-fee-redistributor-updates-mainnet/index.ts
> +  await executePermissionChanges(
which is the final fee we should set then?

2023-06-22 16:17 UTC, facuspagnuolo commented
@dmf7z please take another look, I've added a few changes to disable the withdrawer action on all L2s and disable the swap fee setter action completely. The part missing is the withdraw fee for mainnet.

2023-06-25 02:40 UTC, brunitob commented on constants/tokens/bsc.ts
> +export const WETH = '0x2170Ed0880ac9A755fd29B2688956BD959F933F8'
Confirmed 100% sure it's `0x2170ed0880ac9a755fd29b2688956bd959f933f8` it's the official [Binance-Peg Ethereum Token (ETH)](https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8)

There's no WETH, only Ethereum Token on BSC, but it's a BEP20

2023-06-25 02:40 UTC, brunitob commented on constants/tokens/bsc.ts
> +export const WETH = '0x2170Ed0880ac9A755fd29B2688956BD959F933F8'
Confirmed 100% sure it's `0x2170ed0880ac9a755fd29b2688956bd959f933f8` it's the official [Binance-Peg Ethereum Token (ETH)](https://bscscan.com/token/0x2170ed0880ac9a755fd29b2688956bd959f933f8)

There's no WETH, only Ethereum Token on BSC, but it's a BEP20

2023-06-25 02:40 UTC, brunitob commented on tasks/2023062100-paraswap-fee-redistributor-updates-mainnet/index.ts
> +  await executePermissionChanges(
[Mimic will charge a 2% fee for the assets processed through the Smart Vaults with a 5K USD monthly cap.](https://gov.paraswap.network/t/psp-ip-23-implementing-mimic-smart-vaults-for-fee-collection-and-conversion/1232#h-3-fees-10)

2023-06-25 02:40 UTC, brunitob commented on tasks/2023062100-paraswap-fee-redistributor-updates-mainnet/input.ts
> +  mimic: TESTING_EOA,
Yes, 
`0x26A0c29261d18C49e6Cf0Cee175018274D58f90C` eth, polygon, arb, opt, avax,bsc, 
`0x2D956351fA705a5FCd5fE0e99363Ef9CcCc84921` fantom

@dmf7z lets do ASAP the confirm&migration task.

2023-06-25 02:40 UTC, brunitob commented on tasks/2023062106-paraswap-fee-redistributor-updates-avalanche/input.ts
> +    allowedTokens: [tokens.WETH],
This is ok? Wormhole/CCTP only supports USDC

2023-06-25 02:40 UTC, brunitob commented on tasks/2023062106-paraswap-fee-redistributor-updates-avalanche/input.ts
> +    maxRelayerFeePct: fp(0.05), // 5%
Relayer Fee is always 35 USD, 
5% -> 35 USDC -> min amount to bridge it's 700 USDC
We should set the `maxRelayerFeePct: fp(0.07),`

2023-06-25 02:40 UTC, brunitob commented on tasks/2023062106-paraswap-fee-redistributor-updates-avalanche/input.ts
> +    maxRelayerFeePct: fp(0.05), // 5%
```suggestion
    maxRelayerFeePct: fp(0.07), // 7%
```

2023-06-28 21:11 UTC, dmf7z approved these changes

2023-06-29 13:59 UTC, brunitob approved these changes
Go Go Go

2023-06-29 23:53 UTC, merged